Ventas/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static


app_name="ventas"


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('aplicaciones.base_principal.urls'))),
    path('', include(('aplicaciones.productos.urls'))),
    path('', include(('aplicaciones.ofertas.urls'))),
    path('', include(('aplicaciones.peticiones.urls'))),
    path('', include(('aplicaciones.inventario_stock.urls'))),
    path('', include(('aplicaciones.pdfs.urls'))),
    path('', include(('aplicaciones.usuarios.urls'))),
    path('', include(('aplicaciones.login.urls'))),
    #path('logout/', vistaLogin.Logout.as_view() ,name="logout"),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicaciones/pdfs/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views as vistasPdf

app_name ="pdfs"

urlpatterns = [


    #Para crear los pdfs con clases
    #path('pdf/', vistasPdf.ReportePersonasPDF.as_view() ,name="pdf"),

    #Con argumentos 
    path('pdf/<int:pk>', vistasPdf.ReportePersonasPDF.as_view() ,name="pdf"),

    path('pdf2/', vistasPdf.viewPDF  ,name="pdf2"),

    #path('pdf_3/', vistasPdf.PrivacyPaperPrinter.get_pdf ,name="pdf_3"),
    

    #Pruebas
     #path('pdf_prueba/', vistasPdf.crear_pdf ,name="pdf2"),


    #path('Ofertas_internacionales/', vistasPeticiones.Ofertas_Internacionales.as_view() ,name="OfertasInternacionales"),
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplicaciones/peticiones/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views as vistasPeticiones

app_name ="peticiones"

urlpatterns = [
    

    #Para las peticiones
    path('PeticionCrear/', vistasPeticiones.PeticionCrear_def, name='PeticionCrear'),
    #path('PeticionCrear/', vistasPeticiones.PeticionCrear.as_view() ,name="PeticionCrear"),
    path('PeticionListar/', vistasPeticiones.Peticionlistar.as_view() ,name="PeticionListar"),

    #Url para ver productos de una peticion
    path('Peticion_Productos/<int:pk>/', vistasPeticiones.Peticion_Productos_View.as_view() ,name="Peticion_Productos"),
    #Url para ver procesos de una peticion
    path('Peticion_Procesos/<int:pk>/', vistasPeticiones.Peticion_Procesos_View.as_view() ,name="Peticion_Procesos"),

    #Url para ver aprobar una peticion
    path('Peticion_Aprobar/<int:pk>/', vistasPeticiones.Peticion_Aprobar ,name="Peticion_Aprobar"),

    
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplicaciones/peticiones/models.py
from django.db import models
from django.conf import settings

from aplicaciones.productos.models import Producto

# Create your models here.


class Peticion(models.Model):


    #Con esto determinamos en que proceso se encuentra la peticion
    status_peticion = [
        ('revision','Revisión'), #El administrador debe validar la petición
        #('aprobada','Aprobada'),
        ('oferta','Oferta'), #Los productores pueden ver y ofertar
        ('transporte','Transporte'),#La peticion se hace visible para los transportistas y pueden ofertar para enviar la mercancia
        ('proceso','Proceso de verificación'), #Proceso de verificación
        ('atendida','Atendida'),
        ('cancelada','Cancelada'),
    ]

    #Para determinar que calidad tienen las frutas
    tipo_peticion = [
        ('nacional','Nacional'),
        ('internacional','Internacional'),
    ]
    

    id = models.AutoField(primary_key=True)
    cliente = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="cliente_peticion", on_delete=models.CASCADE,blank=True, null=True)
    #producto = models.ForeignKey(Producto, on_delete=models.CASCADE,blank=False, null=False)
    
    
    tabla_Productos = models.ManyToManyField(Producto,through='Productos_de_Peticion')
    

    #Cada campos re presenta es un proceso de la peticion 
    
    #Proceso de revision con su admin aprobador
    revision = models.BooleanField(default=False)
    aprobado_por = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="aprobado_por", on_delete=models.CASCADE,blank=True, null=True)
    
    #Proceso de oferta con su productor
    oferta = models.BooleanField(default=False)
    productor_elegido = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="productor_peticion", on_delete=models.CASCADE,blank=True, null=True)
    
    #Proceso de transporte con su transportista
    transporte = models.BooleanField(default=False)
    transportista_elegido = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="transportista_peticion", on_delete=models.CASCADE,blank=True, null=True)
    
    #Proceso de verificacion(se lleva a cabo la verificacion)
    proceso_de_verificacion = models.BooleanField(default=False)

    #Proceso de finalización(El cliente aprueba el envio de la mercancia)
    atendido = models.BooleanField(default=False)
    


    
    
    
    #Este campo es para saber en que proceso estamos
    estado_peticion = models.CharField("estado",max_length=150,choices=status_peticion,default='revision',blank=True, null=True)
    tipo_peticion = models.CharField("tipo",max_length=150,choices=tipo_peticion,default='nacional',blank=True, null=True)
    #fecha_caducidad = models.DateField(auto_now_add=False,auto_now=False,blank=True) #Solo fecha

    def __str__(self):
         return "Peticion "+str(self.id)+", de : "+str(self.cliente.username)+", Estatus: "+str(self.estado_peticion)+", Tipo: "+str(self.tipo_peticion)

    class Meta:

        verbose_name = "Peticion"
        verbose_name_plural = "Peticiones"

        permissions = [
            #(Lo que se guarda en bases de datos, lo que se ve al usuario)
            
            #Permisos para iniciar y consultar jugadas
            ("peticiones", "Peticiones"),
            #("consultarjugada", "ConsultarJugada"),

            #Para ver los informes
            #("informejugada", "InformeJugada"),

        ]#Fin de los permisos




class Productos_de_Peticion(models.Model):

    #Para determinar que calidad tienen las frutas
    calidad_producto = [
        ('alta','Alta'),
        ('mediana','Mediana'),
        ('baja','Baja'),
    ]

    id_peticion = models.ForeignKey(Peticion,on_delete=models.CASCADE,blank=True, null=True)
    id_producto = models.ForeignKey(Producto,on_delete=models.CASCADE,blank=True, null=True)

    calidad = models.CharField("calidad",max_length=150,choices=calidad_producto,default='baja',blank=False, null=False)
    cantidad = models.IntegerField(default=1,blank=False,null=False) #En base a Kilogramos(kg)
    #id_usuario = models.ForeignKey(Usuarios, on_delete=models.CASCADE,blank=True, null=True)
    #id_comprobante = models.ForeignKey(Comprobante, on_delete=models.CASCADE,blank=True, null=True)

    #status = models.CharField("status",
    #    max_length=150,
    #    choices=tipo_plan,    
    #    default='Por Pagar'
    #)

    def __str__(self):
        return "Peticion: "+str(self.id_peticion.id) +", de: "+str(self.id_peticion.cliente.username)+" ----- Pedido: "+str(self.id_producto)+" ----- Calidad:"+str(self.calidad)+" ----- Cantidad: "+str(self.cantidad)+"Kg"
        #return "id: "+str(self.id)+", Tipo Jugada: "+str(self.id_jugada.id_tipo_jugada)+", "+str(self.id_jugada)+" "+str(self.id_usuario)+" "+str(self.id_comprobante)+" "+str(self.id_telefono)+" Usuario: "+str(self.id_usuario)+" Status: "+self.status

aplicaciones/peticiones/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,redirect
from django.urls import reverse, reverse_lazy

#Aplicacion de PRODUCTOS
from aplicaciones.usuarios.models import Usuarios

#Aplicacion de PRODUCTOS
from aplicaciones.productos.models import Producto
from aplicaciones.productos.form import ProductoForm

#Aplicacion de PETICIONES
from aplicaciones.peticiones.models import Peticion, Productos_de_Peticion
from aplicaciones.peticiones.form import PeticionPersonalizadoForm,PeticionForm

#Aplicacion de ofertas
from aplicaciones.ofertas.models import Contrato



#Clases para las plantillas
from django.views.generic import View,TemplateView, CreateView, UpdateView, DetailView, ListView, DeleteView

# Create your views here.



######################## PARA LAS PETICIONES ################################################


def PeticionCrear_def(request):
    #verificamos que estamos ogeados
    if request.user.is_authenticated:
        
        contexto = {}
        #Cuando solicitamos una pagina
        if request.method == "GET":
            
            print("ENTRAMOS EN GET PARA CREAR LA PETICION")
            form = PeticionPersonalizadoForm(usuario=request.user)
            contexto = {'form': form,
                        'user': request.user}
            contexto['contrato'] ="SIN CONTRATO"

            contrato_usuario = Contrato.objects.filter(usuario=request.user)
            if contrato_usuario.exists():
                print("Si tiene contrato")
                
                #Verificamos si tiene el contrato vigente
                contrato_vigente = Contrato.objects.get(usuario=self.request.user)
                if contrato_vigente.estado_contrato == "vigente":
                    print("El contrato del usuario:",self.request.user.username,"SI esta vigente.")
                    contexto['ofertas'] = Peticion.objects.filter(tipo_peticion="nacional")
                    contexto['contrato'] ="CONTRATO VIGENTE"

                else:
                    print("El contrato del usuario:",self.request.user.username,"NO esta vigente.")
                    contexto['ofertas'] = Peticion.objects.none()
                    contexto['contrato'] ="CONTRATO CADUCADO"
            else:
                print("No tiene contrato")
                contexto['contrato'] ="SIN CONTRATO"
                #print("entramos en GET:", orden)






        #Metodo(POST)
        else:

            #print(request.POST)
            print("\nEntramos en POST de la peticion\n")
            print(request.POST)
            form = PeticionPersonalizadoForm(data=request.POST,usuario=request.user)

            #Variables para guardar
            productos = request.POST.getlist('productos')
            calidad = request.POST.getlist('calidad')
            cantidad = request.POST.getlist('cantidad')
            
            print(productos," jajajajaja")

            #si el formulario tiene los datos correctos entramos aqui
            
            
            
            if form.is_valid():
            # and trabajo.is_valid() and suministro.is_valid():
            
            
                print("\nEl formulario es correcto")

                #Creamos la peticion primero
                Peticion_Creada = Peticion.objects.create(cliente=request.user)


                #Con este for guardamos los productos en la peticion correspondiente
                for i in range(len(productos)):
                    Productos_de_Peticion.objects.create(
                        id_peticion=Peticion_Creada,
                        id_producto=Producto.objects.get(id=productos[i]),
                        calidad=calidad[i],
                        cantidad=cantidad[i])
                    print(i)




                return redirect('peticiones:PeticionListar')
                #print("entramos aqui en POST")
                #orden = form.save()
                #orden_creada = orden.save(commit=False)
                #print("ORDEN CREADA:",orden_creada)
                #print(orden_creada.id)
                #print(orden_creada.observacion)
                #orden_creada.save()
            
                #print(suministro.cleaned_data)

                
            #    contexto = {'user': request.user,
            #                }
                
            
            
            
            else:

                print("la orden no fue creada...")
                
            # redirect to a new URL:
            return render(request, 'peticiones/peticiones-crear.html',contexto)
    
    
    
    
    #Si el usuario no esta autenticado
    else:

        print("USUARIO NO AUTENTICADO")
        return redirect('/login')


    #print(contexto)
    return render(request, 'peticiones/peticiones-crear.html', contexto)







"""
class PeticionCrear(CreateView):

    model = Peticion  
    #form_class = PeticionPersonalizadoForm
    template_name = "peticiones/peticiones-crear.html"
    success_url = reverse_lazy('peticiones:PeticionListar')

    
    #Para enviar argumentos al formulario
    #def get_form_kwargs(self):
        #kwargs = super(PeticionPersonalizadoForm, self).get_form_kwargs()
        #kwargs['usuario'] = self.request.user
    #    return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['informacion'] = "Hola..."
        context['titulo'] = "Crear Petición"
        return context

    def post(self,request,*args,**kwargs):
        
        print("entrando en post")

        #Si pide argumentos se lo pasamos
        form = PeticionPersonalizadoForm(data=request.POST)#,usuario=self.request.user
        if form.is_valid():
            form.save()#Guardamos el objeto
            return HttpResponseRedirect(self.success_url)

        #En caso de que no se cree el self.object se coloca en None
        self.object = None
        print(form.errors)

        #Aqui llamamos a todas las variables establecidas en get_context
        context = self.get_context_data(**kwargs)
        context['form'] = form

        #Asi es otra forma de enviar el contexto
        return render(request,self.template_name,context)
        
        #Asi es una forma de enviar
        #return render(request,self.template_name,{"form":form})
"""


class Peticionlistar(ListView):

    model = Peticion  
    #form_class = ProductoForm
    context_object_name = 'peticiones'
    template_name = "peticiones/peticiones-listar.html"
    success_url = reverse_lazy('base_principal:index')
    #queryset = Peticion.objects.filter(cliente=request.user) #Esta es una forma


    #Para establecer parametros en context_object_name
    def get_queryset(self):


        #Aqui debemos hacer una logica en caso de que sea administrador o usuario diferente a administrador
        print("Usuario Perfil:",self.request.user.rol)
        if self.request.user.rol == "administrador":
            return Peticion.objects.all() # Get 5 books containing the title war
        else:
            return Peticion.objects.filter(cliente=self.request.user) # Get 5 books containing the title war
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #context['now'] = timezone.now()
        return context







class Peticion_Productos_View(ListView):
    model = Productos_de_Peticion
    context_object_name = "Productos"
    template_name = "peticiones/peticiones-productos.html"

    #Para establecer parametros en context_object_name
    def get_queryset(self):

        #Aqui debemos hacer una logica en caso de que sea administrador o usuario diferente a administrador
        print("Usuario Perfil:",self.request.user.rol,"Variable: ",self.kwargs.get('pk',None))
        return Productos_de_Peticion.objects.filter(id_peticion=self.kwargs.get('pk',None)) # Get 5 books containing the title war
    



    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #print("jajajaja detalles empresa de : ",self.object.id)
        #print(Departamento.objects.filter(empresa_id=self.object.id))
        context['id'] = self.kwargs.get('pk',None)
        context['titulo'] = "Detail Company"
        #context['departamentos'] = Departamento.objects.filter(empresa_id=self.object.id).order_by("-fecha_creacion")
        #context['cantidad_empresas'] = Empresa.objects.filter(creado_por=self.request.user.id).count()
        context['usuario'] = self.request.user
        #context['entrevista_lista'] = Entrevista.objects.filter(departamento_id=self.object.id)
        return context



class Peticion_Procesos_View(DetailView):
    
    model = Peticion
    context_object_name = "peticion"
    template_name = "peticiones/peticiones-procesos.html"

    #Para establecer parametros en context_object_name
    #def get_queryset(self):

        #Aqui debemos hacer una logica en caso de que sea administrador o usuario diferente a administrador
    #    print("Usuario Perfil:",self.request.user.rol,"Variable: ",self.kwargs.get('pk',None))
    #    return Productos_de_Peticion.objects.filter(id_peticion=self.kwargs.get('pk',None)) # Get 5 books containing the title war
    

    


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print("jajajaja detalles peticion de : ",self.object.id)
        context['id'] = self.kwargs.get('pk',None)
        #context['titulo'] = "Detail Company"
        context['usuario'] = self.request.user
        #context['entrevista_lista'] = Entrevista.objects.filter(departamento_id=self.object.id)
        return context



#############################################################################################





###### Para aprobar las peticiones ########

def Peticion_Aprobar(request,pk):
    #verificamos que estamos ogeados
    if request.user.is_authenticated:
        
        contexto = {}

aplicaciones/peticiones/templates/peticiones/peticiones-listar.html
{% extends "base.html" %}
{% load static %}


{% block titulo %}Peticiones | Listar{% endblock %}



{% block enlacessecundariosCSS %}
        
{% endblock %}


{% block menu_superior %}

        <!--Aqui se incluye el menu superior-->
        {% include "menusuperior.html" %}
        
{% endblock%}

{% block menu_lateral %}

        <!--Aqui se incluye el menu superior-->
        {% include "menulateral.html" with person="Jane" %}
            
{% endblock%}

{% block cuerpo %}

                <div id="layoutSidenav_content">
                    <main>
                        <div class="container-fluid px-4">
                            <h1 class="mt-4">Peticiones</h1>
                            <ol class="breadcrumb mb-4">
                            </ol>
                            
                            <div class="card mb-4">
                                <div class="card-header">
                                    <i class="fas fa-table me-1"></i>
                                    Lista de Peticiones
                                </div>
                                <div class="card-body">
                                    
                                    
                                    <table id="datatablesSimple">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Cliente</th>
                                                <th>Aprobado Por</th>
                                                <th>Estado</th>
                                                <th>Opciones</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for peticion in peticiones  %}
                                                <tr>
                                                    <td>{{ forloop.counter }}</td>
                                                    <td>{{ peticion.cliente.username|title }}</td>

                                                    <td>
                                                        {% if peticion.aprobado_por %}
                                                        <p>{{ peticion.aprobado_por.username|upper}}</p>
                                                    {% else %}
                                                        <p>En proceso</p>
                                                    
                                                    {% endif %}
                                                    </td>

                                                    
                                                    <td>{{ peticion.estado_peticion|title}}</td>
                                                    
                                                    <td>

                                                        <a href="{% url 'peticiones:Peticion_Productos' peticion.id %} ">
                                                            <button type="button" class="btn btn-warning"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-seam" viewBox="0 0 16 16">
                                                                <path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5l2.404.961L10.404 2l-2.218-.887zm3.564 1.426L5.596 5 8 5.961 14.154 3.5l-2.404-.961zm3.25 1.7-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z"/>
                                                              </svg>  Productos</button>
                                                        </a>
                                                        


                                                        

                                                        <a href="{% url 'peticiones:Peticion_Procesos' peticion.id %} ">
                                                            <button type="button" class="btn btn-primary">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bezier2" viewBox="0 0 16 16">
                                                                    <path fill-rule="evenodd" d="M1 2.5A1.5 1.5 0 0 1 2.5 1h1A1.5 1.5 0 0 1 5 2.5h4.134a1 1 0 1 1 0 1h-2.01c.18.18.34.381.484.605.638.992.892 2.354.892 3.895 0 1.993.257 3.092.713 3.7.356.476.895.721 1.787.784A1.5 1.5 0 0 1 12.5 11h1a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1-1.5-1.5H6.866a1 1 0 1 1 0-1h1.711a2.839 2.839 0 0 1-.165-.2C7.743 11.407 7.5 10.007 7.5 8c0-1.46-.246-2.597-.733-3.355-.39-.605-.952-1-1.767-1.112A1.5 1.5 0 0 1 3.5 5h-1A1.5 1.5 0 0 1 1 3.5v-1zM2.5 2a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zm10 10a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z"/>
                                                                  </svg> Procesos
                                                            </button>
                                                        </a>

                                                          <button  type="button" class="btn btn-danger">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard2-x" viewBox="0 0 16 16">
                                                                <path d="M9.5 0a.5.5 0 0 1 .5.5.5.5 0 0 0 .5.5.5.5 0 0 1 .5.5V2a.5.5 0 0 1-.5.5h-5A.5.5 0 0 1 5 2v-.5a.5.5 0 0 1 .5-.5.5.5 0 0 0 .5-.5.5.5 0 0 1 .5-.5h3Z"/>
                                                                <path d="M3 2.5a.5.5 0 0 1 .5-.5H4a.5.5 0 0 0 0-1h-.5A1.5 1.5 0 0 0 2 2.5v12A1.5 1.5 0 0 0 3.5 16h9a1.5 1.5 0 0 0 1.5-1.5v-12A1.5 1.5 0 0 0 12.5 1H12a.5.5 0 0 0 0 1h.5a.5.5 0 0 1 .5.5v12a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5v-12Z"/>
                                                                <path d="M8 8.293 6.854 7.146a.5.5 0 1 0-.708.708L7.293 9l-1.147 1.146a.5.5 0 0 0 .708.708L8 9.707l1.146 1.147a.5.5 0 0 0 .708-.708L8.707 9l1.147-1.146a.5.5 0 0 0-.708-.708L8 8.293Z"/>
                                                              </svg>
                                                            Eliminar
                                                        </button>

                                                        {% if user.rol == "administrador" %}
                                                            {% if peticion.estado_peticion != "revision" %}
                                                            
                                                            {% else %}
                                                                <a href="{% url 'peticiones:Peticion_Aprobar' peticion.id %} ">
                                                                    <button type="button" class="btn btn-success">
                                                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-capslock" viewBox="0 0 16 16">
                                                                            <path fill-rule="evenodd" d="M7.27 1.047a1 1 0 0 1 1.46 0l6.345 6.77c.6.638.146 1.683-.73 1.683H11.5v1a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1v-1H1.654C.78 9.5.326 8.455.924 7.816L7.27 1.047zM14.346 8.5 8 1.731 1.654 8.5H4.5a1 1 0 0 1 1 1v1h5v-1a1 1 0 0 1 1-1h2.846zm-9.846 5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1v-1zm6 0h-5v1h5v-1z"/>
                                                                        </svg> Aprobar
                                                                </button>
                                                                </a>
                                                            {% endif %}

                                                            
                                                        {% else %}
                                                            
                                                        {% endif %}

                                                        <!--
                                                        <button type="button" class="btn btn-danger" id={{jugada.id}} data-status="{{jugada.status }}" data-comprobante="{{jugada.id_comprobante.numero_comprobante }}"  onclick="Pagar_Comprobante(this);">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-up-left" viewBox="0 0 16 16">
                                                                <path fill-rule="evenodd" d="M7.364 3.5a.5.5 0 0 1 .5-.5H14.5A1.5 1.5 0 0 1 16 4.5v10a1.5 1.5 0 0 1-1.5 1.5h-10A1.5 1.5 0 0 1 3 14.5V7.864a.5.5 0 1 1 1 0V14.5a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5v-10a.5.5 0 0 0-.5-.5H7.864a.5.5 0 0 1-.5-.5z"/>
                                                                <path fill-rule="evenodd" d="M0 .5A.5.5 0 0 1 .5 0h5a.5.5 0 0 1 0 1H1.707l8.147 8.146a.5.5 0 0 1-.708.708L1 1.707V5.5a.5.5 0 0 1-1 0v-5z"/>
                                                              </svg> <span>Pagar</span> 
                                                          </button>
                                                          -->
                                                    </td>
                                                </tr>
                                                <tr>
                                                        
                                                </tr>
                                                
                                            {% empty %}
                                                <li>No hay Peticiones</li>
                                            {% endfor %}
                                            
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </main>
                    <footer class="py-4 bg-light mt-auto">
                        <div class="container-fluid px-4">
                            <div class="d-flex align-items-center justify-content-between small">
                                <div class="text-muted">Copyright &copy; Maipo Grande 2022</div>
                                <div>
                                    <a href="#">Privacy Policy</a>
                                    &middot;
                                    <a href="#">Terms &amp; Conditions</a>
                                </div>
                            </div>
                        </div>
                    </footer>
                </div>
            
            {% endblock%}



            {% block enlacesprincipalesJS %}
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
            <script src="{% static 'js/scripts.js' %}"></script>
            {% endblock %}

            {% block enlacessecundariosJS %}
                <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
                <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
                <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
                <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
                <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
            {% endblock %}