Ventas/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static


app_name="ventas"


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('aplicaciones.base_principal.urls'))),
    path('', include(('aplicaciones.productos.urls'))),
    path('', include(('aplicaciones.ofertas.urls'))),
    path('', include(('aplicaciones.peticiones.urls'))),
    path('', include(('aplicaciones.inventario_stock.urls'))),
    path('', include(('aplicaciones.pdfs.urls'))),
    path('', include(('aplicaciones.usuarios.urls'))),
    path('', include(('aplicaciones.login.urls'))),
    #path('logout/', vistaLogin.Logout.as_view() ,name="logout"),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicaciones/base_principal/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views as vistasBasePrincipal


app_name ="base_principal"

urlpatterns = [
    

    
    path('', vistasBasePrincipal.Index.as_view() ,name="index"),




    #Para las apis
    #path('probando/', views.Probando ,name="probando"),
    #path('api_login/', views.api_login ,name="api_login"),

    
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplicaciones/login/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views as vistasLogin

app_name ="login"

urlpatterns = [
    

    
    path('login/', vistasLogin.Login.as_view() ,name="login"),
    path('logout/', vistasLogin.Logout.as_view() ,name="logout"),
    




    #Para las apis
    #path('probando/', views.Probando ,name="probando"),
    #path('api_login/', views.api_login ,name="api_login"),

    
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplicaciones/ofertas/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views as vistasPeticiones

app_name ="ofertas"

urlpatterns = [


     #Para las ofertas nacionales e internacionales
    path('Ofertas_nacionales/', vistasPeticiones.Ofertas_Nacionales.as_view() ,name="OfertasNacionales"),
    path('Ofertas_internacionales/', vistasPeticiones.Ofertas_Internacionales.as_view() ,name="OfertasInternacionales"),

    #Ofertas que lanzan los productores
    #path('Productor_oferta/', vistasPeticiones.Ofertas_Internacionales.as_view() ,name="OfertasInternacionales"),
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplicaciones/productos/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views as vistasProductos

app_name ="productos"

urlpatterns = [
    

    #Para los productos
    path('ProductoCrear/', vistasProductos.ProductosCrear.as_view() ,name="ProductosCrear"),
    path('ProductoListar/', vistasProductos.Productoslistar.as_view() ,name="ProductoListar"),

    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplicaciones/usuarios/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views as VistasUsuario

app_name ="usuarios"

urlpatterns = [


    path('perfil', VistasUsuario.Perfil_Usuario.as_view(), name='perfil'),
    #path('login/', vistasLogin.Login.as_view() ,name="login"),
    
    #path('', views.index.as_view() ,name="index"),



    
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplicaciones/base_principal/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
#Estos dos modelos son para crear permisos personalizados
from django.contrib.auth.models import Permission,Group



#Clases para las plantillas
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView, ListView, DeleteView

    



class Index(TemplateView):

    template_name = "index.html"

    def dispatch(self, request, *args, **kwargs):

        if request.user.is_anonymous:
            print("No estas autenticado, eres un usuario anonimo")
            return redirect("login:login")

        else:

            print("Estas autenticado GENIAL")
            #print("Permisos: ",list(Permission.objects.all()))
            print("usuario: ",request.user," Cantidad de Grupos: ",Group.objects.all().count())

            #GCliente = Group.objects.get(name="cliente_E")

            print("\n\n")
            #print("\n\nPermisos Grupo Productor: ",GProductor.permissions.all() )
            #for elemento in GCliente.permissions.all():
            #    print(elemento.name)
            #print("\n\n")

            #Grupo_productor.permissions.set(Permission.objects.get(name="Can add inventario"),
            print("administrador:",request.user.groups.filter(name='administrador').exists())
            print("productor:",request.user.groups.filter(name='productor').exists())
            print("cliente :",request.user.groups.filter(name='cliente').exists())
            print("\n\n")
            #print("usuario permisos: ",request.user.get_all_permissions())
            #print(request.user.has_perm('src.ver_zulia'))
            #print("uSUARIO : ",request.user.has_module_perms())
            
            #Aqui verificamos si el usuario esta activo para que ingrese
            ''' 
            if request.user.activo:   
                print("Usuario activo y validado")
            else:
                print("El usuario no esta activo")
                messages.add_message(request, messages.INFO, "Usuario Inactivo")
                return redirect("src:logout")
            '''

            #return redirect("src:index")
            #print("Usuario ",request.user)

            #Esto es algo que podria funcionar en algun momento
            #grupo="prueba"
            #print('Proyecto %s' % (grupo))

            

            
            #empresa_creada = Empresa.objects.filter(creado_por_id=request.user.id)


        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['informacion'] = "Hola..."

aplicaciones/base_principal/templates/index.html
{% extends "base.html" %}
{% load static %}


{% block titulo %}Inicio{% endblock %}



{% block enlacessecundariosCSS %}
        
{% endblock %}


{% block menu_superior %}

        <!--Aqui se incluye el menu superior-->
        {% include "menusuperior.html" %}
        
{% endblock%}

{% block menu_lateral %}

        <!--Aqui se incluye el menu superior-->
        {% include "menulateral.html" with person="Jane" %}
            
{% endblock%}

{% block cuerpo %}

                <div id="layoutSidenav_content">
                    <main>
                        <div class="container-fluid px-4">
                            <h1 class="mt-4">Tablero</h1>
                            <ol class="breadcrumb mb-4">
                                <li class="breadcrumb-item active">Tablero</li>
                            </ol>
                            <div class="row">
                                <div class="col-xl-3 col-md-6">
                                    <div class="card bg-primary text-white mb-4">
                                        <div class="card-body">Primary Card</div>
                                        <div class="card-footer d-flex align-items-center justify-content-between">
                                            <a class="small text-white stretched-link" href="#">View Details</a>
                                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-3 col-md-6">
                                    <div class="card bg-warning text-white mb-4">
                                        <div class="card-body">Warning Card</div>
                                        <div class="card-footer d-flex align-items-center justify-content-between">
                                            <a class="small text-white stretched-link" href="#">View Details</a>
                                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-3 col-md-6">
                                    <div class="card bg-success text-white mb-4">
                                        <div class="card-body">Success Card</div>
                                        <div class="card-footer d-flex align-items-center justify-content-between">
                                            <a class="small text-white stretched-link" href="#">View Details</a>
                                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-3 col-md-6">
                                    <div class="card bg-danger text-white mb-4">
                                        <div class="card-body">Danger Card</div>
                                        <div class="card-footer d-flex align-items-center justify-content-between">
                                            <a class="small text-white stretched-link" href="#">View Details</a>
                                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xl-6">
                                    <div class="card mb-4">
                                        <div class="card-header">
                                            <i class="fas fa-chart-area me-1"></i>
                                            Area Chart Example
                                        </div>
                                        <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
                                    </div>
                                </div>
                                <div class="col-xl-6">
                                    <div class="card mb-4">
                                        <div class="card-header">
                                            <i class="fas fa-chart-bar me-1"></i>
                                            Bar Chart Example
                                        </div>
                                        <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
                                    </div>
                                </div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">
                                    <i class="fas fa-table me-1"></i>
                                    DataTable Example
                                </div>
                                <div class="card-body">
                                    <table id="datatablesSimple">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Position</th>
                                                <th>Office</th>
                                                <th>Age</th>
                                                <th>Start date</th>
                                                <th>Salary</th>
                                            </tr>
                                        </thead>
                                        <tfoot>
                                            <tr>
                                                <th>Name</th>
                                                <th>Position</th>
                                                <th>Office</th>
                                                <th>Age</th>
                                                <th>Start date</th>
                                                <th>Salary</th>
                                            </tr>
                                        </tfoot>
                                        <tbody>
                                            
                                            
                                            <tr>
                                                <td>Lael Greer</td>
                                                <td>Systems Administrator</td>
                                                <td>London</td>
                                                <td>21</td>
                                                <td>2009/02/27</td>
                                                <td>$103,500</td>
                                            </tr>
                                            <tr>
                                                <td>Jonas Alexander</td>
                                                <td>Developer</td>
                                                <td>San Francisco</td>
                                                <td>30</td>
                                                <td>2010/07/14</td>
                                                <td>$86,500</td>
                                            </tr>
                                            <tr>
                                                <td>Shad Decker</td>
                                                <td>Regional Director</td>
                                                <td>Edinburgh</td>
                                                <td>51</td>
                                                <td>2008/11/13</td>
                                                <td>$183,000</td>
                                            </tr>
                                            <tr>
                                                <td>Michael Bruce</td>
                                                <td>Javascript Developer</td>
                                                <td>Singapore</td>
                                                <td>29</td>
                                                <td>2011/06/27</td>
                                                <td>$183,000</td>
                                            </tr>
                                            <tr>
                                                <td>Donna Snider</td>
                                                <td>Customer Support</td>
                                                <td>New York</td>
                                                <td>27</td>
                                                <td>2011/01/25</td>
                                                <td>$112,000</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </main>
                    <footer class="py-4 bg-light mt-auto">
                        <div class="container-fluid px-4">
                            <div class="d-flex align-items-center justify-content-between small">
                                <div class="text-muted">Copyright &copy; Your Website 2022</div>
                                <div>
                                    <a href="#">Privacy Policy</a>
                                    &middot;
                                    <a href="#">Terms &amp; Conditions</a>
                                </div>
                            </div>
                        </div>
                    </footer>
                </div>
            
            {% endblock%}



            {% block enlacessecundariosJS %}
                <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
                <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
                <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
                <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
                <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
            {% endblock %}

aplicaciones/base_principal/templates/menulateral.html
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Inicio</div>
                <a class="nav-link" href="{% url 'base_principal:index' %}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Tablero
                </a>

                {% if perms.productos.add_producto %}

                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#menuOferta" aria-expanded="false" aria-controls="menuOferta">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Ofertas
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="menuOferta" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{% url 'ofertas:OfertasNacionales' %}">Nacionales</a>
                        <a class="nav-link" href="{% url 'ofertas:OfertasInternacionales' %}">Internacionales</a>
                    </nav>
                </div>
                {% endif %}
                
                
                {% if perms.peticiones.peticiones %}
                <div class="sb-sidenav-menu-heading">Ordenes</div>

                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#menuPeticion" aria-expanded="false" aria-controls="menuPeticion">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Peticiones
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="menuPeticion" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        {% if user.rol == "administrador" %}

                        {% else %}
                            <a class="nav-link" href="{% url 'peticiones:PeticionCrear' %}">Crear Petición</a>
                        {% endif %}
                        
                        <a class="nav-link" href="{% url 'peticiones:PeticionListar' %}">Listar Peticiones</a>
                    </nav>
                </div>
                {% endif %}

                {% if perms.productos.add_producto %}
                <div class="sb-sidenav-menu-heading">Ventas</div>

                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#menuProducto" aria-expanded="false" aria-controls="menuProducto">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Productos
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="menuProducto" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{% url 'productos:ProductosCrear' %}">Crear Producto</a>
                        <a class="nav-link" href="{% url 'productos:ProductoListar' %}">Listar Productos</a>
                    </nav>
                </div>
                {% endif %}


                {% if perms.inventario_stock.add_inventario %}
                <div class="sb-sidenav-menu-heading">Inventario  </div>

                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#menuInventario" aria-expanded="false" aria-controls="menuInventario">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Inventarios
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="menuInventario" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        {% if user.rol != "administrador" %}
                        <a class="nav-link" href="{% url 'inventario_stock:InventarioAsignar' %}">Agregar Producto</a>
                        {% endif %}
                        <a class="nav-link" href="{% url 'inventario_stock:InventarioListar' %}">Listar Inventario</a>
                    </nav>
                </div>
                {% endif %}

               

                <!-- 
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                    <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                    Categorias
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                            Authentication
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="login.html">Login</a>
                                <a class="nav-link" href="register.html">Register</a>
                                <a class="nav-link" href="password.html">Forgot Password</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                            Error
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="401.html">401 Page</a>
                                <a class="nav-link" href="404.html">404 Page</a>
                                <a class="nav-link" href="500.html">500 Page</a>
                            </nav>
                        </div>
                    </nav>
                </div>
                <div class="sb-sidenav-menu-heading">Addons</div>
                <a class="nav-link" href="charts.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                    Charts
                </a>
                <a class="nav-link" href="tables.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                    Tables
                </a>
            -->
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Bienvenido:</div>
            <span>{{user.username|title}}</span>
        </div>
    </nav>
</div>

aplicaciones/base_principal/templates/menusuperior.html
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="{% url 'base_principal:index' %}">Maipo Grande{{person}}
    </a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Buscar..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
    </form>
    <!-- Navbar-->
    <div class="dropdown">
        <button type="button" class="badge rounded-pill bg-light text-dark position-relative" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell" viewBox="0 0 16 16">
                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
              </svg>
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
              99+
              <span class="visually-hidden">mensajes no leídos</span>
            </span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item" href="#">Notificacion 1</a></li>
            <li><a class="dropdown-item" href="#">Notificacion 2</a></li>
            <li><a class="dropdown-item" href="#">Notificacion 3</a></li>
          </ul>

    </div>
    





    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'usuarios:perfil' %}">Perfil</a></li>
                <li><a class="dropdown-item" href="#!">Actividades</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="{% url 'login:logout' %}">Cerrar Sesion</a></li>
            </ul>
        </li>
    </ul>
</nav>